# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os.path
import subprocess
from pathlib import Path

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.Create_Button = QtWidgets.QPushButton(Widget, clicked=lambda: self.createFile())
        self.Create_Button.setGeometry(QtCore.QRect(10, 20, 87, 26))
        font = QtGui.QFont()
        font.setBold(True)
        self.Create_Button.setFont(font)
        self.Create_Button.setObjectName("Create_Button")
        self.Create_Path = QtWidgets.QLineEdit(Widget)
        self.Create_Path.setGeometry(QtCore.QRect(110, 20, 271, 26))
        self.Create_Path.setObjectName("Create_Path")
        self.Delete_Path = QtWidgets.QLineEdit(Widget)
        self.Delete_Path.setGeometry(QtCore.QRect(520, 20, 271, 26))
        self.Delete_Path.setObjectName("Delete_Path")
        self.Delete_Button = QtWidgets.QPushButton(Widget, clicked=lambda: self.deleteFile())
        self.Delete_Button.setGeometry(QtCore.QRect(420, 20, 87, 26))
        font = QtGui.QFont()
        font.setBold(True)
        self.Delete_Button.setFont(font)
        self.Delete_Button.setObjectName("Delete_Button")
        self.Rename_Button = QtWidgets.QPushButton(Widget, clicked=lambda: self.renameFile())
        self.Rename_Button.setGeometry(QtCore.QRect(10, 60, 87, 26))
        font = QtGui.QFont()
        font.setBold(True)
        self.Rename_Button.setFont(font)
        self.Rename_Button.setObjectName("Rename_Button")
        self.Rename_Path_Old = QtWidgets.QLineEdit(Widget)
        self.Rename_Path_Old.setGeometry(QtCore.QRect(110, 60, 271, 26))
        self.Rename_Path_Old.setObjectName("Rename_Path_Old")
        self.Rename_Path_New = QtWidgets.QLineEdit(Widget)
        self.Rename_Path_New.setGeometry(QtCore.QRect(520, 60, 271, 26))
        self.Rename_Path_New.setObjectName("Rename_Path_New")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(420, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(170, 90, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Signal_Value = QtWidgets.QLineEdit(Widget)
        self.Signal_Value.setGeometry(QtCore.QRect(110, 100, 51, 26))
        self.Signal_Value.setObjectName("Signal_Value")
        self.PID_Value = QtWidgets.QLineEdit(Widget)
        self.PID_Value.setGeometry(QtCore.QRect(260, 100, 121, 26))
        self.PID_Value.setObjectName("PID_Value")
        self.Signal_Button = QtWidgets.QPushButton(Widget, clicked=lambda: self.sendSignal())
        self.Signal_Button.setGeometry(QtCore.QRect(10, 100, 87, 26))
        font = QtGui.QFont()
        font.setBold(True)
        self.Signal_Button.setFont(font)
        self.Signal_Button.setObjectName("Signal_Button")
        self.Fork_Button = QtWidgets.QPushButton(Widget, clicked=lambda: self.fork())
        self.Fork_Button.setGeometry(QtCore.QRect(420, 100, 87, 26))
        font = QtGui.QFont()
        font.setBold(True)
        self.Fork_Button.setFont(font)
        self.Fork_Button.setObjectName("Fork_Button")
        self.OnePipe_Button = QtWidgets.QPushButton(Widget, clicked=lambda: self.pipe())
        self.OnePipe_Button.setGeometry(QtCore.QRect(560, 100, 87, 26))
        font = QtGui.QFont()
        font.setBold(True)
        self.OnePipe_Button.setFont(font)
        self.OnePipe_Button.setObjectName("OnePipe_Button")
        self.TwoPipes_Button = QtWidgets.QPushButton(Widget, clicked=lambda: self.pipes())
        self.TwoPipes_Button.setGeometry(QtCore.QRect(700, 100, 87, 26))
        font = QtGui.QFont()
        font.setBold(True)
        self.TwoPipes_Button.setFont(font)
        self.TwoPipes_Button.setObjectName("TwoPipes_Button")
        self.label_4 = QtWidgets.QLabel(Widget)
        self.label_4.setGeometry(QtCore.QRect(420, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.TextToWrite_Value = QtWidgets.QLineEdit(Widget)
        self.TextToWrite_Value.setGeometry(QtCore.QRect(110, 140, 271, 26))
        self.TextToWrite_Value.setObjectName("TextToWrite_Value")
        self.Write_Path = QtWidgets.QLineEdit(Widget)
        self.Write_Path.setGeometry(QtCore.QRect(520, 140, 271, 26))
        self.Write_Path.setObjectName("Write_Path")
        self.Write_Button = QtWidgets.QPushButton(Widget, clicked=lambda: self.Write())
        self.Write_Button.setGeometry(QtCore.QRect(10, 140, 87, 26))
        font = QtGui.QFont()
        font.setBold(True)
        self.Write_Button.setFont(font)
        self.Write_Button.setObjectName("Write_Button")
        self.Read_Button = QtWidgets.QPushButton(Widget, clicked=lambda: self.Read())
        self.Read_Button.setGeometry(QtCore.QRect(10, 180, 87, 26))
        font = QtGui.QFont()
        font.setBold(True)
        self.Read_Button.setFont(font)
        self.Read_Button.setObjectName("Read_Button")
        self.Read_Path = QtWidgets.QLineEdit(Widget)
        self.Read_Path.setGeometry(QtCore.QRect(110, 180, 271, 26))
        self.Read_Path.setObjectName("Read_Path")
        self.Console = QtWidgets.QPlainTextEdit(Widget)
        self.Console.setGeometry(QtCore.QRect(13, 220, 771, 371))
        self.Console.setObjectName("Console")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.Create_Button.setText(_translate("Widget", "Create"))
        self.Delete_Button.setText(_translate("Widget", "Delete"))
        self.Rename_Button.setText(_translate("Widget", "Rename"))
        self.label_2.setText(_translate("Widget", "New Path:"))
        self.label_3.setText(_translate("Widget", "To Process:"))
        self.Signal_Button.setText(_translate("Widget", "Send Signal"))
        self.Fork_Button.setText(_translate("Widget", "fork"))
        self.OnePipe_Button.setText(_translate("Widget", "One Pipe"))
        self.TwoPipes_Button.setText(_translate("Widget", "Two Pipes"))
        self.label_4.setText(_translate("Widget", "In Path:"))
        self.Write_Button.setText(_translate("Widget", "Write"))
        self.Read_Button.setText(_translate("Widget", "Read"))

    def createFile(self):
        path = self.Create_Path.text()
        if self.isFileExists("Create"):
            os.system("rm Create")
        command = "gcc -o Create Create.c; " + "./Create " + path
        s = subprocess.check_output(command, shell=True, encoding="utf8", errors="ignore")
        self.Console.setPlainText(s)
        if self.isFileExists("Create"):
            os.system("rm Create")
        self.Create_Path.clear()

    def deleteFile(self):
        path = self.Delete_Path.text()
        if self.isFileExists("Delete"):
            os.system("rm Delete")
        command = "gcc -o Delete Delete.c; " + "./Delete " + path
        s = subprocess.check_output(command, shell=True, encoding="utf8", errors="ignore")
        self.Console.setPlainText(s)
        if self.isFileExists("Delete"):
            os.system("rm Delete")
        self.Delete_Path.clear()

    def renameFile(self):
        old_path = self.Rename_Path_Old.text()
        new_path = self.Rename_Path_New.text()
        if self.isFileExists("Rename"):
            os.system("rm Rename")
        command = "gcc -o Rename Rename.c; " + "./Rename " + old_path + " " + new_path
        s = subprocess.check_output(command, shell=True, encoding="utf8", errors="ignore")
        self.Console.setPlainText(s)
        if self.isFileExists("Rename"):
            os.system("rm Rename")
        self.Rename_Path_New.clear()
        self.Rename_Path_Old.clear()


    def sendSignal(self):
        sig = self.Signal_Value.text()
        pid = self.PID_Value.text()
        if self.isFileExists("Signal"):
            os.system("rm Signal")
        command = "gcc -o Signal Signal.c; " + "./Signal " + sig + " " + pid
        s = subprocess.check_output(command, shell=True, encoding="utf8", errors="ignore")
        self.Console.setPlainText(s)
        if self.isFileExists("Signal"):
            os.system("rm Signal")
        self.Signal_Value.clear()
        self.PID_Value.clear()


    def fork(self):
        if self.isFileExists("Fork"):
            os.system("rm Fork")
        command = "gcc -o Fork Fork.c; " + "./Fork"
        s = subprocess.check_output(command, shell=True, encoding="utf8", errors="ignore")
        self.Console.setPlainText(s)
        if self.isFileExists("Fork"):
            os.system("rm Fork")


    def pipe(self):
        if self.isFileExists("Pipe"):
            os.system("rm Pipe")
        command = "gcc -o Pipe Pipe.c; " + "./Pipe"
        s = subprocess.check_output(command, shell=True, encoding="utf8", errors="ignore")
        self.Console.setPlainText(s)
        if self.isFileExists("Pipe"):
            os.system("rm Pipe")

    def pipes(self):
        if self.isFileExists("Pipes"):
            os.system("rm Pipes")
        command = "gcc -o Pipes Pipes.c; " + "./Pipes"
        s = subprocess.check_output(command, shell=True, encoding="utf8", errors="ignore")
        self.Console.setPlainText(s)
        if self.isFileExists("Pipes"):
            os.system("rm Pipes")

    def Write(self):
        path = self.Write_Path.text()
        txt = self.TextToWrite_Value.text()
        os.system("touch Write_TempFile")
        tempfile = open("Write_TempFile", "w")
        tempfile.write(txt)
        tempfile.close()

        if self.isFileExists("Write"):
            os.system("rm Write")
        command = "gcc -o Write Write.c; " + "./Write " + path + " Write_TempFile"
        s = subprocess.check_output(command, shell=True, encoding="utf8", errors="ignore")
        self.Console.setPlainText(s)
        if self.isFileExists("Write"):
            os.system("rm Write")
        if self.isFileExists("Write_TempFile"):
            os.system("rm Write_TempFile")
        self.Write_Path.clear()
        self.TextToWrite_Value.clear()


    def Read(self):
        path = self.Read_Path.text()
        if self.isFileExists("Read"):
            os.system("rm Read")
        command = "gcc -o Read Read.c; " + "./Read " + path
        s = subprocess.check_output(command, shell=True, encoding="utf8", errors="ignore")
        self.Console.setPlainText(s)
        if self.isFileExists("Read"):
            os.system("rm Read")
        self.Read_Path.clear()




    def isFileExists(self, filepath):
        return os.path.isfile(filepath)

    def isDirectoryExists(self, dirpath):
        return os.path.isdir(dirpath)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
